data_path: 'data/data_SMPBind_sample_1000.csv'
col_prots: 'Sequence'
col_mols: 'SMILES'
d_model: 1024
num_heads: 8
ff_hidden_layer: 4096
dropout: 0.1
num_layers: 4
batch_size: 10
num_epochs: 10
learning_rate: 0.0001
loss_function: 'crossentropy'
label_smoothing: False
optimizer: 'AdamW'
weight_decay: 0.001
betas: [0.9, 0.999]
weights_path: 'weights/best_model_weights.pth'
validation_split: 0.2
get_wandb: False
wandb_project: 'train_decoder_parallel'
wandb_name: 'decoder'
num_gpus: 2
verbose: 2
prot_max_length: 600
mol_max_length: 80
es_patience: 5
es_delta: 0.0001
scheduled_sampling: 1
seed: 1234
checkpoint_epoch: True
resume_training: False